name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Installer les dépendances
      run: |
        pip install -r requirements.txt

    - name: Lancer l’application (test)
      run: |
        python app.py &
        sleep 5
        curl http://localhost:5000
